### ISSUE TITLE
Errors with new beta

### ISSUE THREAD

**Issue by guilhermepovala** [glzawalski/WorkoutKit-Builder#2]
Hello,

I want to try your project, but I'm facing a lot of errors on Version 15.0 beta 6 (15A5219j).

Do you have any plans on updating the repository?

**Comment by glzawalski** [comment]
Hello. Thanks for checking out my demo app.

Since this seems to be a recurring issue with breaking changes between beta versions I'll be taking a look into it to update to Beta 6 (15A5218j)

**Comment by glzawalski** [comment]
I have updated the codebase to work on the new API changes. They way I have initially set up my views is causing some problems after Apple's changes, so it still requires more work to completely refactor, but it's at least functional for now.

Be warned that trying to create invalid combinations of activity types and workout goals will cause a crash instead of the old alert that used to set up. Check `Known Issues` on readme for an example.
